DATABASE_URL = "postgresql://postgres.hgiufiapsqvtvyseizox:Zawadi01%2A@aws-1-eu-north-1.pooler.supabase.com:6543/postgres?sslmode=require"
TREASURER_PASSWORD = "zawadi01*"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "zawadicourt@gmail.com"
SMTP_APP_PASSWORD = "wuhd wstp uasc ygwg"

[gcp_service_account]
type = "service_account"
project_id = "YOUR_PROJECT_ID"
private_key_id = "YOUR_PRIVATE_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-sa@your-project.iam.gserviceaccount.com"
client_id = "YOUR_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-sa%40your-project.iam.gserviceaccount.com"

gs_backup_spreadsheet_id = "YOUR_SPREADSHEET_ID"